### ISSUE TITLE
Thesaurus: Rename NA into SN (?) like Scope note

### ISSUE THREAD

**Issue by cpagenstecher** [renderpci/dedalo-4#12]
Instead of too many abbreviations, maybe simply write: scope | observations | code

![grafik](https://cloud.githubusercontent.com/assets/26455443/24248877/781b4864-0fd1-11e7-9599-472d69815dc3.png)

**Comment by renderpci** [comment]
We agree the translation/change of the "NA" to "SN" (Spanish abbreviation to English abbreviation).

But we don't see the solution of full names. In the thesaurus you need focus to the descriptor term, and the other fields is a "facility" access to it or "fast and easy" access but is not the main function, we think that the full names will be "noise" in the list.

Maybe, can be a solution do a icon for every field or group it and show when you click?

**Comment by cpagenstecher** [comment]
I think "scope" is 5 letters instead o 2 letters for "SN", "code" is not much more than "OF". But this is not important for us, you decide.

**Comment by renderpci** [comment]
done!
