### ISSUE TITLE
No chance to set admin's password

### ISSUE THREAD

**Issue by julmarfur** [renderpci/dedalo-4#16]
After installing JQuery and Bootstrap and running Dédalo into the Browser, it requests me a username and a password, so I have no chance to set the admin's one (as it is said in the installation procedure instructions).

![dedalo_inipage](https://cloud.githubusercontent.com/assets/26466489/24415006/592da8f8-13e0-11e7-8775-65fc0519063b.png)

**Comment by renderpci** [comment]
What version are you install?

**Comment by julmarfur** [comment]
Dédalo 4

**Comment by renderpci** [comment]
Dédalo 4.0?

**Comment by renderpci** [comment]
Can you do a var_dump in the test_su_default_password() function of class.login.php and send me the result?

change the file:

/lib/dedalo/login/class.login.php

in the line 787:

> public function test_su_default_password() {
> ...
> $dato 		= $component->get_dato();	

after the line that get_dato add:

> **var_dump($dato);**

and re-run the login.
send me the result of the code that you will see in the browser or the error log of php.

**Comment by julmarfur** [comment]
![var_dump](https://cloud.githubusercontent.com/assets/26466489/24456659/06b303c0-1494-11e7-8358-a99a7a2d0cad.png)
![var_dump](https://cloud.githubusercontent.com/assets/26466489/24456662/0924e5a6-1494-11e7-8dee-10d92a4c171e.png)

**Comment by renderpci** [comment]
this error is not about Dedalo, is of your connection, you need send me the var_dump of the php, it can be in the browser or in your log files.

**Comment by julmarfur** [comment]
I tell php.ini to save the error_log at /var/log/php-scripts.log, but it does not appear.
![error_log_php_path](https://cloud.githubusercontent.com/assets/26466489/24510333/34dbb6a4-1569-11e7-8c4e-27d109004a55.png)

What is more, httpd error_log says that there is an error in core_functions.php in Dédalo configuration files. Exactly lines 307 and 362:
![httpd_errorlog](https://cloud.githubusercontent.com/assets/26466489/24510494/b2b2b460-1569-11e7-89ec-bbb903adab08.png)
![error_line307](https://cloud.githubusercontent.com/assets/26466489/24510503/b579fcb2-1569-11e7-8c81-6b9a5411f0b3.png)
![error_line362](https://cloud.githubusercontent.com/assets/26466489/24510511/ba057e5a-1569-11e7-8bbc-fff3d0b33fa6.png)

**Comment by julmarfur** [comment]
We are installing Dédalo 4.5.1.ei12

**Comment by renderpci** [comment]
Hi 

Normally you can show the var_dump  in the browser. Something similar to:

string(0) "gfbuVr574rg&7yhvs"

And, read the var_ dump official description:

http://php.net/manual/en/function.var-dump.php

**Comment by renderpci** [comment]
Hi

I see that the error is in login. You have the last version(4.5.1, OpenSSL), but the login is read the previous codification of the Pw(4.0.24, mycript) and stop the config. Ok, I change the login code. Please download the new login file and run again.

**Comment by julmarfur** [comment]
Okey, it "works". I set the root password but when I reload the page it asks me to set it again and says: ERROR! THIS IS ALREADY CONFIGURED!
![almost](https://cloud.githubusercontent.com/assets/26466489/24613633/245d6e94-1889-11e7-8490-f019dbbbafbe.png)

**Comment by renderpci** [comment]
Appears that your install file is locked.
You need check that file 
`/install/set_psw/trigger.set_psw.php`
is "stopped". (Check and remove first line of code if you see a die()/exit() sentence abobe this line:
```
<?php
$TOP_TIPO=false;
require_once( dirname(dirname(dirname(__FILE__))) .'/lib/dedalo/config/config4.php');)
...
```
to unlock the file and try again the set password process.

**Comment by julmarfur** [comment]
I did it and reconfigured root's password. It happens again

**Comment by renderpci** [comment]
Check your file: /install/set_psw/trigger.set_psw.php and search this code in first line: 

```
<?php # Remove this line and the next line to re-configure the application
      die('Error: Sorry, the application has already been configured.');
```

Remove the line and try login again.

Good luck

**Comment by julmarfur** [comment]
I did it
![trigger1](https://cloud.githubusercontent.com/assets/26466489/24944611/3e56e990-1f5c-11e7-97bd-622c64f41a8d.png)
![trigger2](https://cloud.githubusercontent.com/assets/26466489/24944613/406260d4-1f5c-11e7-8ac2-575a5f15ebb8.png)
However, after configuring the password for "root" again, if appears the message "already configured".
![magic](https://cloud.githubusercontent.com/assets/26466489/24944663/684b7824-1f5c-11e7-9cc0-74ae66ffcec2.png)

**Comment by renderpci** [comment]
Ok, I test your context case and the problem is with encrypt / decrypt phase. 
The result of the decryption in login window is giving false, so the application interprets that the password has not yet been set.
You have a problem with your constant 'DEDALO_INFORMACION' value placed in config/config4_db.php or with your root password, or both.
Remove the lock line mentioned above again and try another combination of values for the variable 'DEDALO_INFORMACION' and / or the password for the root.
(Try to have the length of the variables do not exceed 16 characters)
