### ISSUE TITLE
Some users don't see the Thesaurus terms

### ISSUE THREAD

**Issue by cpagenstecher** [renderpci/dedalo-4#17]
for example Damian, who is Adminstrator - I see it, however.
![grafik](https://cloud.githubusercontent.com/assets/26455443/24417561/2533aecc-13e9-11e7-8e54-2b6479449334.png)

**Comment by renderpci** [comment]
We think that is a css font problem no a "security" profile problem.

**Comment by renderpci** [comment]
The bug was repair.
