### ISSUE TITLE
Can't enter to root user on Dédalo 4.0.23

### ISSUE THREAD

**Issue by julmarfur** [renderpci/dedalo-4#18]
I've already set the "root" password but, when I try to log in it says that my password is already configured but it doesn't let me log in.

**Comment by renderpci** [comment]
Are you installed the last version? (4.0.23).

In the version 4.0.22 the pw encryption was changed from mycript to OpenSSL. Is possible that you have a conflict with the original install pw.

Please check if you have the last version.

**Comment by julmarfur** [comment]
I've solved that. Now it says that root user does not exist when I try to log in.

**Comment by renderpci** [comment]
Hi

Oh Yes!, in the version 4.0.21 the conponent_input_text was changed to array:

"root" -> ["root"]

So, log into the postgreSQL and change it to the string version (remove the array brackets). Probe it and if it work update Dédalo.

**Comment by julmarfur** [comment]
Thank you, it worked!

**Comment by renderpci** [comment]
You welcome!
