### ISSUE TITLE
Duplicate code on sample.config4.php

### ISSUE THREAD

**Issue by lrullo** [renderpci/dedalo-4#3]
Duplicate code in sample.config4.php:

redefined variables on lines 180:192

SLOW_QUERY_MS
DEDALO_BACKUP_ON_LOGIN
DEDALO_BACKUP_TIME_RANGE

Defined on lines 104:115

**Comment by renderpci** [comment]
Yes, duplicate code.

For fixit: delete the lines: 179 to 194.

I change the sample.config4.php.
Now the file is correct.
