### ISSUE TITLE
DEDALO_PREFIX_TIPOS need 'ich'

### ISSUE THREAD

**Issue by lrullo** [renderpci/dedalo-4#4]
At line 250
	define('DEDALO_PREFIX_TIPOS', serialize( array('dd','rsc','oh') ));
change to
	define('DEDALO_PREFIX_TIPOS', serialize( array('dd','rsc','oh','ich') ));
if not

Exception Object
(
    [message:protected] => Error Processing Request. parent wrong tipo 'ich1' 
    [string:Exception:private] => 
    [code:protected] => 1
    [file:protected] => /opt/dedalo-4/lib/dedalo/db/class.RecordObj_descriptors_dd.php
    [line:protected] => 37
    [trace:Exception:private] => Array

**Comment by renderpci** [comment]
This not a issue. 
If you need the "ich" (Intangible Cultural Heritage), you can put into the DEDALO_PREFIX_TIPOS. 
In the v4, the install base is "dd"(Dédalo Database), "rsc" (Resources) and "oh" (Oral History) but "ich"... ummm... can be use or not... 
We need document it.

And the question is:
ICH need go to the base install?. (for me... I think yes...)

**Comment by lrullo** [comment]
The problem is: admin web interface don't init if this "tipo" is not active in DEDALO_PREFIX_TIPOS using your dedalo4_install database.

**Comment by adev-test** [comment]
Originally, we don't think include 'ich' as default prefix. I think now is a good moment, although configuration of 'ich' file is not tested enough.
Ok, I change this config adding 'ich' as prefix (included in install database)

**Comment by renderpci** [comment]
Ok, we don't change the "dedalo4_install" and the prefix go to config.
Final config:
define('DEDALO_PREFIX_TIPOS', serialize( array('dd','rsc','oh','ich') ));
Note: the ich need to be more tested, and need more CSS refine for the records. (similar to OH).
