### ISSUE TITLE
PDFjs - viewer_dedalo.html

### ISSUE THREAD

**Issue by lrullo** [renderpci/dedalo-4#6]
When PDF is open, Dedalo use dedalo_viewer.html
Ex:
http://192.168.1.221/dedalo/lib/pdfjs/web/dedalo_viewer.html?pdf_url=/dedalo/media/pdf/standar/rsc165_rsc245_1.pdf?t=1464793022

Is this viewer_dedalo.html a modification of viewer.html?

**Comment by renderpci** [comment]
Yes. Please, use custom dedalo_viewer.html (viewer.html is overwrited by updates)

**Comment by lrullo** [comment]
Where i can download this custom viewer?
I search in your repository and  i dont find this file.

**Comment by renderpci** [comment]
You can use now new viewer (4.0.11) directly from component_pdf (Please view component_pdf/html/component_pdf_viewer.php) and config paths to your instalation.
