### ISSUE TITLE
Function array() error in new update

### ISSUE THREAD

**Issue by lrullo** [renderpci/dedalo-4#7]
.../dedalo-4/lib/dedalo/area/class.area.php

[02/06/16 16:58:27]	dd_error::captureShutdown	Ops.. [Fatal Error] Call to undefined function arra() 
<pre>Array
(
    [type] => 1
    [message] => Call to undefined function arra()
    [file] => /opt/dedalo-4/lib/dedalo/area/class.area.php
    [line] => 178
)

Change function arra() to array()

**Comment by devpacdd** [comment]
Thanks lrullo. Fixed

**Comment by renderpci** [comment]
Fixed and close the issue
