### ISSUE TITLE
Add a "Translated" field in the "Audiovisual/Process" area

### ISSUE THREAD

**Issue by cpagenstecher** [renderpci/dedalo-4#9]
![grafik](https://cloud.githubusercontent.com/assets/26455443/23997575/1a9f1ba4-0a52-11e7-8eb7-b9553cf2241e.png)

**Comment by renderpci** [comment]
We think that is a good addition for control the process of work.

READY: Added the new field to the resources and re-position all the fields of process group:

The new fields will be in structure =>: 
**Dédalo4 Benimamet 17-03-2017 17:44.**

We will upload in the next commit.
